name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate PR
    if: ${{ github.actor != 'release-bot[bot]' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Simulate merge
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin ${{ github.base_ref }}
          git checkout -b pr-validation origin/${{ github.base_ref }}
          git merge --no-commit --no-ff ${{ github.event.pull_request.head.sha }}

      - name: Install system dependencies for Python build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev \
            libbz2-dev libreadline-dev libsqlite3-dev curl \
            libncursesw5-dev xz-utils tk-dev libxml2-dev \
            libxmlsec1-dev libffi-dev liblzma-dev bc

      - name: Install ASDF
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.15.0
          echo "$HOME/.asdf/bin" >> $GITHUB_PATH
          echo "$HOME/.asdf/shims" >> $GITHUB_PATH
          source $HOME/.asdf/asdf.sh

      - name: Install ASDF plugins and tools
        run: |
          cd $GITHUB_WORKSPACE
          cat .tool-versions | cut -d' ' -f1 | xargs -I{} asdf plugin add {} || true
          asdf install
          asdf reshim

      - name: Install dependencies
        run: make configure

      - name: Lint code
        run: make lint

      - name: Build CLI test
        run: make build-cli

      - name: Run unit tests
        run: make unit-test

      - name: Run functional tests
        run: make functional-test
        
      - name: Run example tests
        run: make test-example

      - name: Check test coverage
        id: coverage
        run: |
          REQUIRED_COVERAGE=40
          COVERAGE=$(make test-coverage-json | jq -r '.combined_total | rtrimstr("%") | tonumber')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < $REQUIRED_COVERAGE" | bc -l) )); then
            echo "Test coverage is below ${REQUIRED_COVERAGE}% ($COVERAGE%)"
            exit 1
          fi
          echo "Test coverage is $COVERAGE% (meets minimum requirement of ${REQUIRED_COVERAGE}%)"
